#!/usr/bin/env bash
# Used to cleanup files generated by other scripts
# Will delete everything that is not an SRT file (unless it's a split SRT file which has -000.srt where 000 is any 3 num
# GLOBAL VARS ARE HERE
source ~/.opensubtitles_project

DATA_DIR="$SUBTITLE_DATA/processed"

if [ -z "$1" ]; then
    read -p "Would you like to clean all directories under $DATA_DIR? (Yn)" CONFIRM
    if [ "$CONFIRM" == 'y' ]; then
        SEARCH_PATH="$DATA_DIR"
    fi
else
    SEARCH_PATH="$1"
    if [ ! -d "$SEARCH_PATH" ]; then
        echo "PATH is not a valid directory."
        exit 1
    fi
fi

# Make sure not to match info.txt, .*gold.txt or original subtitles which have 4-10 digit names
find -E "$SEARCH_PATH" -type f \
    ! -iregex '.+gold.txt' \
    ! -iname 'info.txt' \
    ! -iregex '.+vecalign.path' \
    ! -iregex '.*[0-9]{4,10}.srt' \
    ! -iregex '.*[0-9]{4,10}.sent' \
    ! -iregex '.*[0-9]{4,10}.sent-index' \
    -exec rm -f {} \;

if [ "$2" == "-a" ]; then
    find -E "$SEARCH_PATH" -type f \
    ! -iregex '.+gold.txt' \
    ! -iname 'info.txt' \
    ! -iregex '.*[0-9]{4,10}.srt' \
    -exec rm -f {} \;
fi
