
if [ -z "$SUBTITLE_REPO" ]; then
    echo "Please set SUBTITLE_REPO environment variable to the root of this repository."
    exit 1
fi

#PREPROCESSING
VOCAB_SIZE=32000

# GENERAL
SEED=1234
SOURCE="eng"
TARGET="spa"
DIR="$SUBTITLE_REPO/language_model/vocab_$VOCAB_SIZE"
PRED_FILE="$DIR/predictions.$SOURCE-$TARGET.txt"
IN_DIR="$DIR/input"
PREPROCESSED_DIR="$DIR/preprocessed"
TOKENS_DIR="$DIR/tokens"
mkdir -p "$IN_DIR"
mkdir -p "$PREPROCESSED_DIR"
mkdir -p "$TOKENS_DIR"

# TRAINING
MAX_EPOCHS=1
LAYERS=6
ACTIVATION="relu"
ARCHITECTURE="transformer"
DROPOUT=0.2
LEARNING_RATE=0.0005
EMBED_DIM=256
HIDDEN_DIM=1024
HEADS=8
WARMUP=4000
INIT_LEARNING_RATE="1.5e-06"
WEIGHT_DECAY="0.0001"
CRITERION="label_smoothed_cross_entropy"
LABEL_SMOOTHING="0.05"
SCORING="bleu"
OPTIMIZER="adam"
CLIP_NORM="1.0"
MAX_TOKENS="3000"
MAX_UPDATES="400000"
UPDATE_FREQUENCY=8
PATIENCE=5
STOP_MIN_LEARNING_RATE="1e-06"
SAVE_INTERVAL="1"
SAVE_DIR="$DIR/emb_${EMBED_DIM}-hid_$HIDDEN_DIM-warm_$WARMUP-dropo_$DROPOUT-maxtokens_$MAX_TOKENS-layers_$LAYERS-heads_$HEADS"

# GENERATE
BEAM=5
BATCH_SIZE=256
BUFFER_SIZE=2000